name: "Internal release (auth mobile)"

on:
    workflow_dispatch: # Allow manually running the action

env:
    FLUTTER_VERSION: "3.24.3"
<<<<<<< HEAD
<<<<<<<< HEAD:.github/workflows/auth-internal-release.yml
========

permissions:
    contents: write
>>>>>>>> upstream/main:.github/workflows/mobile-internal-release.yml
=======

permissions:
    contents: write
>>>>>>> upstream/main

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
<<<<<<< HEAD
<<<<<<<< HEAD:.github/workflows/auth-internal-release.yml
                working-directory: auth
========
                working-directory: mobile/apps/photos
>>>>>>>> upstream/main:.github/workflows/mobile-internal-release.yml
=======
                working-directory: mobile/apps/auth
>>>>>>> upstream/main

        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Install Flutter ${{ env.FLUTTER_VERSION  }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION  }}
                  cache: true

            - name: Setup keys
              uses: timheuer/base64-to-file@v1
              with:
                  fileName: "keystore/ente_auth_key.jks"
                  encodedString: ${{ secrets.SIGNING_KEY }}

            - name: Build PlayStore AAB
              run: |
<<<<<<< HEAD
<<<<<<<< HEAD:.github/workflows/auth-internal-release.yml
                  flutter build appbundle --release --flavor playstore --dart-define=app.flavor=playstore
========
                  flutter build appbundle --dart-define=cronetHttpNoPlay=true --release --flavor playstore
>>>>>>>> upstream/main:.github/workflows/mobile-internal-release.yml
=======
                  flutter build appbundle --dart-define=cronetHttpNoPlay=true --release --flavor playstore
>>>>>>> upstream/main
              env:
                  SIGNING_KEY_PATH: "/home/runner/work/_temp/keystore/ente_auth_key.jks"
                  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
                  SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

            - name: Upload AAB to PlayStore
              uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
<<<<<<< HEAD
<<<<<<<< HEAD:.github/workflows/auth-internal-release.yml
                  packageName: io.ente.auth
                  releaseFiles: auth/build/app/outputs/bundle/playstoreRelease/app-playstore-release.aab
========
                  packageName: io.ente.photos
                  releaseFiles: mobile/apps/photos/build/app/outputs/bundle/playstoreRelease/app-playstore-release.aab
>>>>>>>> upstream/main:.github/workflows/mobile-internal-release.yml
=======
                  packageName: io.ente.auth
                  releaseFiles: mobile/apps/auth/build/app/outputs/bundle/playstoreRelease/app-playstore-release.aab
>>>>>>> upstream/main
                  track: internal

            - name: Notify Discord
              uses: sarisia/actions-status-discord@v1
              with:
                  webhook: ${{ secrets.DISCORD_INTERNAL_RELEASE_WEBHOOK }}
                  nodetail: true
<<<<<<< HEAD
                  title: "ðŸ† Internal release Photos (Branch: ${{ github.ref_name }})"
                  description: "[Download](https://play.google.com/store/apps/details?id=io.ente.photos)"
                  color: 0x00ff00
=======
                  title: "ðŸ† Internal release available for Auth"
                  description: "[Download](https://play.google.com/store/apps/details?id=io.ente.auth)"
                  color: 0x800080
>>>>>>> upstream/main
